### ISSUE TITLE
Possible Questions

### ISSUE THREAD

**Issue by Cameron-Cn** [Cameron-Cn/starbucks_2019#2]
> We have a lot of store data, but not much anything about revenue or Starbucks' profitability (aside from the SEC filings).

1) If we are to track `Sales` (or `Profit`) I can think of a few angles:
+ how close the next Starbucks is (do they hurt or help eachother?)
+ how many have opened/closed in region in past year (SEC data is 2013-2017)
+ Price of coffee on global market (Joel said he was looking into it)

2) Sales or potential in Fairfax, SC 
+ We can change this to any city (US or otherwise, though US is easier to get data for)
+ Based on similar criteria as above

Coordinating work on GitHub is tricky, but there's actually a lot of neat features!

**Comment by ghorellana** [comment]
I've included new functionality to the web presentation: iFrame to work with exterior websites for example Tableau Public and data resources. Thanks
